config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'milk_products#index'
    resources :milk_products do
      get :edit_detail, on: :member
      put :change_status, on: :member
    end
  end
  devise_for :admin_users, only: :sessions

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

app/models/milk_attribute.rb
class MilkAttribute < ActiveRecord::Base
  belongs_to :milk_product
end

app/models/milk_brand.rb
class MilkBrand < ActiveRecord::Base
  has_many :milk_products, dependent: :destroy
end

app/models/milk_category.rb
class MilkCategory < ActiveRecord::Base
  has_many :milk_products, dependent: :destroy
end

app/models/milk_extra_attribute.rb
class MilkExtraAttribute < ActiveRecord::Base
  belongs_to :milk_product
end

app/models/milk_product.rb
class MilkProduct < ActiveRecord::Base
  belongs_to :milk_brand
  belongs_to :milk_category
  has_many :milk_attributes, dependent: :destroy
  has_many :milk_extra_attributes, dependent: :destroy
  has_many :milk_product_images, dependent: :destroy
  accepts_nested_attributes_for :milk_attributes, allow_destroy: true
  accepts_nested_attributes_for :milk_extra_attributes, allow_destroy: true
  accepts_nested_attributes_for :milk_product_images, allow_destroy: true
end

app/models/milk_product_image.rb
class MilkProductImage < ActiveRecord::Base
  belongs_to :milk_product
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin/milk_products_controller.rb
class Admin::MilkProductsController < AdminController
  before_action :load_product, only: [:show, :edit]
  def index
    if params[:status].present?
      @products = MilkProduct.includes(:milk_brand).where(published: (params[:status] == 'published'))
    else
      @products = MilkProduct.includes(:milk_brand)
    end
  end

  def show
  end

  def edit
  end

  def update
    @product = MilkProduct.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to admin_milk_product_path(@product)
    else
      flash.now[:error] = @product.errors.full_messages
      render :edit
    end
  end

  def edit_detail
    @product = MilkProduct.find(params[:id])
  end

  def change_status
    @product = MilkProduct.find(params[:id])
    @product.update_attributes!(published: !@product.published)
  end

  private
  def load_product
    @product = MilkProduct.includes(:milk_brand, :milk_product_images, :milk_attributes, :milk_extra_attributes).find(params[:id])
  end

  def product_params
    params.require(:milk_product).permit(:id, :price, :milk_brand_id, :detail, milk_product_images_attributes: [:id, :image, :_destroy], milk_attributes_attributes: [:id, :value], milk_extra_attributes_attributes: [:id, :name, :value])
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/currency_helper.rb
module CurrencyHelper
  def to_currency(number)
    number_to_currency(number, unit: "đ", delimiter: ".", format: "%n %u", precision: 0)
  end
end

app/views/admin/milk_products/_filters.html.erb
<div class="row col-sm-12 form-group">
  <div class="col-sm-1"><strong>STATUS:</strong></div>
  <div class="btn-group col-sm-2">
    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%=params[:status].try(:camelize) || 'All'%>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to 'All', admin_milk_products_path%></li>
      <li><%= link_to 'Published', admin_milk_products_path(status: :published)%></li>
      <li><%= link_to 'Hidden', admin_milk_products_path(status: :hidden)%></li>
    </ul>
  </div>

  <div class="col-sm-1"><strong>PRICE:</strong></div>
  <div class="col-sm-1"><strong>From:</strong></div>
  <div class="col-sm-2">
    <input id="min" class= "col-sm-2 form-control"/>
  </div>
  <div class="col-sm-1"><strong>To:</strong></div>
  <div class="col-sm-2">
    <input id="max" class= "form-control"/>
  </div>
</div>

<div class="row col-sm-12 form-group">
</div>

app/views/admin/milk_products/_form.html.haml
= flash_messages
= form_for [:admin, @product] do |form|
  .container
    .row.form-group
      %label{for: :name} Tên Sản Phẩm:
      = form.text_field :name, class: 'form-control'
    .row.form-group
      %label{for: :milk_brand_id} Thương Hiệu:
      = form.select :milk_brand_id, MilkBrand.pluck(:name, :id), {include_blank: false}, class: 'form-control'
    .row.form-group
      %label{for: :price} Giá:
      = form.text_field :price, class: 'form-control'
    .row.form-group
      %label{for: :milk_extra_attributes} Đặc Điểm Sản Phẩm:
      = form.fields_for :milk_extra_attributes do |attribute|
        = render 'milk_extra_attribute_fields', f: attribute
      .links
        = link_to_add_association '+', form, :milk_extra_attributes, class: 'btn btn-sm btn-primary'

    .row.form-group
      %label{for: :milk_attributes} Đặc Tính Sản Phẩm:
      = form.fields_for :milk_attributes do |attribute|
        = render 'milk_attribute_fields', f: attribute
      .links
        = link_to_add_association '+', form, :milk_attributes, class: 'btn btn-sm btn-primary'


    .btn.btn-info#btn-edit-images Show Images
    .row.form-group#edit-images-group.hidden
      %label{for: :milk_product_images} Images
      = form.fields_for :milk_product_images do |product_image|
        = render 'milk_product_image_fields', f: product_image
      .links
        = link_to_add_association '+', form, :milk_product_images, class: 'btn btn-sm btn-primary'
    .text-center
      = form.submit (@product.new_record? ? 'Create' : 'Update'), class: 'btn btn-success edit-product-btn btn-large'

:javascript
  $('#btn-edit-images').click(show_and_hide_images_group);

  function show_and_hide_images_group(){
    if(($('#edit-images-group').hasClass('hidden'))){
      $('#edit-images-group').removeClass('hidden');
      $('#btn-edit-images').html('Hide Images');
    } else {
      $('#edit-images-group').addClass('hidden');
      $('#btn-edit-images').html('Show Images');
    }
  }

app/views/admin/milk_products/_milk_attribute_fields.html.haml
.nested-fields.col-sm-12
  .field.col-sm-6
    = f.text_field :value, class: 'form-control attribute'
  .col-sm-6
    = link_to_remove_association "X", f, class: 'btn btn-danger btn-sm'
  %hr

app/views/admin/milk_products/_milk_extra_attribute_fields.html.haml
.nested-fields.col-xs-12
  .field.col-sm-2
    = f.text_field :name, class: 'form-control attribute'
  .field.col-sm-4
    = f.text_field :value, class: 'form-control attribute'
  .col-sm-6
    = link_to_remove_association "X", f, class: 'btn btn-danger btn-sm'
  %hr

app/views/admin/milk_products/_milk_product_image_fields.html.haml
.nested-fields
  .field
    .col-lg-5
      = f.file_field :image
    = image_tag f.object.image.url(:medium) if f.object.image?
  = link_to_remove_association "X", f, class: 'btn btn-danger btn-sm'
  %hr

app/views/admin/milk_products/change_status.js.erb
var url = '<%=change_status_admin_milk_product_path(@product)%>';
<% if @product.published %>
  $('a[href="' + url + '"]').attr('class', 'btn btn-info');
  $('a[href="' + url + '"]' + ' span').attr('class', 'glyphicon glyphicon-ok');
<% else %>
  $('a[href="' + url + '"]').attr('class', 'btn btn-danger');
  $('a[href="' + url + '"]' + ' span').attr('class', 'glyphicon glyphicon-remove');
<% end %>

app/views/admin/milk_products/edit.html.haml
%h1.text-center #{@product.id}. #{@product.name}
%br
  = render 'form'

app/views/admin/milk_products/edit_detail.html.haml
%h1.text-center #{@product.id}. #{@product.name}
%br
.container-fluid
  = form_for [:admin, @product] do |form|
    %label{for: :detail} Thông Tin Sản Phẩm:
    = form.text_area :detail, class: 'form-control', rows: 50
    %br
    .text-center.edit-product-btn
      = form.submit 'Update', class: 'btn btn-primary'

app/views/admin/milk_products/index.html.erb
<h1 class="text-center">Products</h1>
<div class="container">
  <%= render 'filters' %>
  <br/>
  <table id="products" class="table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Brand</th>
        <th>Price</th>
        <th>SKU</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%=product.name%></td>
          <td><%=product.milk_brand.name%></td>
          <td class="price"><%=to_currency(product.price)%></td>
          <td><%=product.bibomart_sku%></td>
          <td class= 'text-center'>
            <%= link_to edit_admin_milk_product_path(product), class: 'btn btn-primary' do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>

            <%= link_to admin_milk_product_path(product), class: 'btn btn-success' do %>
              <span class="glyphicon glyphicon-eye-open"></span>
            <% end %>

            <%= link_to edit_detail_admin_milk_product_path(product), class: 'btn btn-success' do %>
              <span class="glyphicon glyphicon-list-alt"></span>
            <% end %>

            <% if product.published %>
              <%= link_to change_status_admin_milk_product_path(product), method: :put, remote: true, class: 'btn btn-info' do %>
                <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            <% else %>
              <%= link_to change_status_admin_milk_product_path(product), method: :put, remote: true, class: 'btn btn-danger' do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
$.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
        var min = $('#min').val() * 1;
        var max = $('#max').val() * 1;
        var price = parseFloat( data[2] ) || 0; // use data for the price column
 
        if ( ( min == '' && max == '' ) ||
             ( min == '' && price <= max ) ||
             ( min <= price && '' == max ) ||
             ( min <= price && price <= max ) )
        {
            return true;
        }
        return false;
    }
);

$(document).ready(function() {
  var table = $('#products').DataTable(
      {
        "pageLength": 50
      }
      );


  $('#min, #max').keyup(function() {
    var new_val = addThousandsSeparator($(this).val().replace(/\./, ''));
    if (new_val != $(this).val()) {
      $(this).val(new_val);
    }

    table.draw();
  });

} );

function addThousandsSeparator(x) {
    //remove commas
    retVal = x ? parseFloat(x.replace(/,/g, '')) : 0;

    //apply formatting
    return retVal.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
}
</script>

app/views/admin/milk_products/show.html.haml
%h1.text-center #{@product.name}
%br
.container-fluid
  .row
    .title.col-sm-1.text-uppercase 
      %strong Thông Tin Sản Phẩm:
    .detail.text-justify.col-sm-11
      = simple_format(@product.detail)
  = link_to 'Chỉnh sửa thông tin sản phẩm', edit_detail_admin_milk_product_path(@product), class: 'btn btn-primary edit-product-btn'
  %hr
  .row
    .title.col-sm-1.text-uppercase 
      %strong Đặc Tính Sản Phẩm:
    .detail.text-justify.col-sm-11
      %ul
        - @product.milk_attributes.each do |attribute|
          %li #{attribute.value}
  %hr
  .row
    .title.col-sm-1.text-uppercase 
      %strong Đặc Điểm Sản Phẩm:
    .detail.text-justify.col-sm-11
      - @product.milk_extra_attributes.each do |extra_attribute|
        .col-sm-12
          .col-sm-2 #{extra_attribute.name}
          .col-sm-10 #{extra_attribute.value}
  %hr
  .row
    .title.col-sm-1.text-uppercase 
      %strong Thương Hiệu:
    .detail.text-justify.col-sm-11
      %h4 #{@product.milk_brand.name}
  %hr
  .row
    .title.col-sm-1.text-uppercase 
      %strong Giá:
    .detail.text-justify.col-sm-11
      %strong.lead #{to_currency(@product.price)}
      %span (#{@product.last_price_change.try(:to_formatted_s,:long)})
  %hr
  .row
    .title.col-sm-1.text-uppercase 
      %strong Hình Ảnh:
    .detail.text-justify.col-sm-11
      - @product.milk_product_images.each do |product_image|
        = link_to product_image.image.url, target: "_blank" do
          %span
            %img{src: product_image.image.url(:medium), size: "300x300"}
.text-center
  = link_to 'Chỉnh sửa chung', edit_admin_milk_product_path(@product), class: 'btn btn-primary edit-product-btn'

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin BeKhoe</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BiboCrawler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>